- docs/Release-Process.md
https://jira.catena-x.net/browse/CPLP-1575
> docs: cplp-1575 - add release-process

- docs/Architecture (coming soon)/Architecture Constraints.md
- docs/Architecture (coming soon)/Building block view
- docs/Architecture (coming soon)/Building block view.md
- docs/Architecture (coming soon)/Context and scope.md
- docs/Architecture (coming soon)/Development Concept.md
- docs/Architecture (coming soon)/Requirements.md
- docs/Architecture (coming soon)/Solution strategy.md
- docs/Architecture (coming soon)/Whitebox Overall System.md
- docs/Architecture (coming soon)/operational-concept.md
Initial version, a number of changes will be still needed; but this version will create the initial documentation ;)
> Add Arc42 docu

- .github/workflows/build.yml
- .github/workflows/kics.yml
- .github/workflows/release.yml
- .github/workflows/trivy.yml
https://jira.catena-x.net/browse/CPLP-1641
> build: cplp-1641 - add workflows for build and securtiy scans

- public/assets/content/de/usecase.json
- public/assets/content/en/usecase.json
connected to pr: https://github.com/catenax-ng/tx-portal-frontend/pull/141
> UseCase-Intro-Traceability-Content Update

- .conf/Dockerfile
- .github/workflows/veracode.yaml
- package.json
add temp fix for cve-2023-0286
remove latest tag
add veracode scan
> fix: resolve security issues

- public/assets/content/de/companyroles.json
- public/assets/content/de/usecase.json
- public/assets/content/en/companyroles.json
- public/assets/content/en/usecase.json
connected with image cleanup in portal repo
> fixed image link

- public/documentation/js/Main.js
- public/documentation/js/State.js
- public/documentation/js/Toolkit.js
Reverts catenax-ng/tx-portal-assets#102
> Revert "fixed links in md files"

- developer/01. Onboarding/03. Registration Approval/03. Registration Approval Process.md
enhance registration approval flow dev
> (updates)-developer-docu-registration-flow

- .conf/Dockerfile
- .github/workflows/build.yml
- add temp fix for CVE-2023-23916
- remove obsolete temp fix for CVE-2023-0286
> fix(cve-2023-23916): add package upgrade as temp fix

- public/assets/content/en/usecase.json
> change(usecases): traceability description updated

- .github/workflows/trivy-main.yml
- .github/workflows/trivy.yml
- .tractusx
- https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5
ref.: CPLP-2334
- chore(trivy) set to fixed container registry
> chore(trg and trivy): add repo metafile and fixed container registry

- developer/Technical Documentation/Dev Process/Dev-flow_git-diagram.md
- developer/Technical Documentation/Operations/Release-Process.md
- update release process to prepare handover
ref: CPLP-2413
> docs(release): update process

- CHANGELOG.md
- DEPENDENCIES
- package.json
> release(1.2.0): merge release into main

- developer/Technical Documentation/Identity & Access/05. Roles & Rights Concept.md
> changed(devDocu): roles & rights matrix

- .conf/Dockerfile
- .github/workflows/build.yml
- .github/workflows/kics.yml
- .github/workflows/release-candidate.yml
- .github/workflows/release.yml
- fix(cve-2023-0464): add temp fix
ref: CPLP-2456
- chore(workflows): update actions
- chore(workflows): direct dispatch to renamed workflow file
- build(env): add build workflow for v1.3.0 release candidate phase
ref: CPLP-2330
> chore(enabler): actions+security upgrades and add build workflow for v1.3.0

- CHANGELOG.md
- package.json
Reviewed-By: Evelyn Gurschler <evelyn.gurschler@bmw.de>
> release(1.3.0-RC1): merge release into main

- public/documentation/index.html
- scripts/build.sh
Reverts catenax-ng/tx-portal-assets#163
didn't solve the issue as expected
> Revert "workaround(documentation): wrong mime type from ingress controller"

- .github/workflows/release-release_candidate.yml
- .github/workflows/release.yml
for git and npm version matching check
ref: CPLP-2564
> fix: change syntax in if statement

- public/assets/content/de/companyRoleChange.json
- public/assets/content/en/companyRoleChange.json
This PR related to CPLP-1532
This sample file is required to fetch this data and display into overlay.
> feat(content): add static content for company role change

- developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
> feat(offers): add technical user profile description

- developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
> chore: add impact on existing data for tu profiles

- developer/Technical Documentation/Others/Notifications.md
remove PUT endpoint - this was a test endpoint only and is not needed anymore
> enhance devDocu/Notifications
